# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vote Presidente' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Bond', '~> 6.0-beta'
  pod 'NVActivityIndicatorView', '~> 3.7.0'
  pod 'RAMAnimatedTabBarController'

  target 'Vote PresidenteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Vote PresidenteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
